In [1]:
print('hello')

hello


In [3]:
9+8

17

In [4]:
age = 21
name = "Astitv Nagpal"

In [5]:
print("The student details are: age = {} and name = {}".format(age, name))

The student details are: age = 21 and name = Astitv Nagpal


In [6]:
s = "123456789"


In [7]:
s[0]

'1'

In [8]:
s[0:]

'123456789'

In [9]:
s[0:4]


'1234'

In [10]:
s[4:2]

''

In [11]:
my_list = ['a', 'b', 'c', 'd']

In [12]:
my_list[0]

'a'

In [13]:
my_list[0]='dfds'

In [14]:
my_list

['dfds', 'b', 'c', 'd']

In [15]:
my_list[0:]='zzzz'

In [16]:
my_list

['z', 'z', 'z', 'z']

In [17]:
my_list[1:2]='zzzz'


In [18]:
my_list

['z', 'z', 'z', 'z', 'z', 'z', 'z']

In [19]:
arr=[1,2,3,4]

In [20]:
arr[0]

1

In [21]:
arr[0:]=9

TypeError: can only assign an iterable

In [22]:
arr[0:]='9'


In [23]:
arr


['9']

In [30]:
se1 = [1,2,3,4,5]

In [31]:
list(map(lamda(num: num*3), seq))

SyntaxError: invalid syntax (<ipython-input-31-748769ea0851>, line 1)

In [29]:
list(map(lambda num: num*3, sel))

NameError: name 'sel' is not defined

In [34]:
seq = [1,2,3,4,5]

In [36]:
list(map(lambda num: num*3, seq))

[3, 6, 9, 12, 15]

In [37]:
import numpy as np

In [38]:
list = [1,2,3]

In [39]:
np.array(list)

array([1, 2, 3])

In [40]:
list=[[1,2,3],[4,5,6],[7,8,9]]

In [41]:
print(list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [44]:
arr=np.array(list)

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
np.arange(5, 101, 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [48]:
np.zeros((5,10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [50]:
np.ones((4,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [51]:
np.linspace(1,10,100)

array([  1.        ,   1.09090909,   1.18181818,   1.27272727,
         1.36363636,   1.45454545,   1.54545455,   1.63636364,
         1.72727273,   1.81818182,   1.90909091,   2.        ,
         2.09090909,   2.18181818,   2.27272727,   2.36363636,
         2.45454545,   2.54545455,   2.63636364,   2.72727273,
         2.81818182,   2.90909091,   3.        ,   3.09090909,
         3.18181818,   3.27272727,   3.36363636,   3.45454545,
         3.54545455,   3.63636364,   3.72727273,   3.81818182,
         3.90909091,   4.        ,   4.09090909,   4.18181818,
         4.27272727,   4.36363636,   4.45454545,   4.54545455,
         4.63636364,   4.72727273,   4.81818182,   4.90909091,
         5.        ,   5.09090909,   5.18181818,   5.27272727,
         5.36363636,   5.45454545,   5.54545455,   5.63636364,
         5.72727273,   5.81818182,   5.90909091,   6.        ,
         6.09090909,   6.18181818,   6.27272727,   6.36363636,
         6.45454545,   6.54545455,   6.63636364,   6.72

In [52]:
np.linspace(1,20,50)

array([  1.        ,   1.3877551 ,   1.7755102 ,   2.16326531,
         2.55102041,   2.93877551,   3.32653061,   3.71428571,
         4.10204082,   4.48979592,   4.87755102,   5.26530612,
         5.65306122,   6.04081633,   6.42857143,   6.81632653,
         7.20408163,   7.59183673,   7.97959184,   8.36734694,
         8.75510204,   9.14285714,   9.53061224,   9.91836735,
        10.30612245,  10.69387755,  11.08163265,  11.46938776,
        11.85714286,  12.24489796,  12.63265306,  13.02040816,
        13.40816327,  13.79591837,  14.18367347,  14.57142857,
        14.95918367,  15.34693878,  15.73469388,  16.12244898,
        16.51020408,  16.89795918,  17.28571429,  17.67346939,
        18.06122449,  18.44897959,  18.83673469,  19.2244898 ,
        19.6122449 ,  20.        ])

In [53]:
np.random.rand(5,5)

array([[ 0.82269387,  0.40872248,  0.32772471,  0.19894095,  0.62988733],
       [ 0.56428242,  0.93460215,  0.99394925,  0.00479984,  0.77328271],
       [ 0.19115623,  0.36334056,  0.97909521,  0.72286327,  0.42303916],
       [ 0.82616527,  0.92955919,  0.56264575,  0.33156885,  0.91867529],
       [ 0.9473299 ,  0.99451257,  0.71675841,  0.22260652,  0.70108271]])

In [54]:
arr=np.arange(25)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
arr=np.arange(27)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [62]:
arr=arr.reshape(3,3,3)

In [64]:
arr.shape

(3, 3, 3)

In [65]:
arr.dtype

dtype('int64')

In [67]:
arr=np.arange(10)

In [68]:
arr=np.arange(10)

In [69]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
new_arr=arr[0:6]

In [71]:
new_arr

array([0, 1, 2, 3, 4, 5])

In [72]:
new_arr[:]=100

In [73]:
new_arr


array([100, 100, 100, 100, 100, 100])

In [74]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9])

In [75]:
new_arr=arr.copy()

In [76]:
new_arr


array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9])

In [77]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9])

In [78]:
new_arr[:]=1

In [79]:
new_arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [80]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9])

In [82]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [83]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
arr[2][2]

9

In [88]:
arr[:1][1:]

array([], shape=(0, 3), dtype=int64)

In [89]:
arr[:2,1:]

array([[2, 3],
       [5, 6]])

In [90]:
arr=np.arange(10)

In [91]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [93]:
arr_bool=arr>5

In [94]:
arr_bool

array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [95]:
arr(arr_bool)

TypeError: 'numpy.ndarray' object is not callable

In [96]:
arr[arr_bool]

array([6, 7, 8, 9])

In [97]:
arr[arr>5]

array([6, 7, 8, 9])

In [98]:
arr=np.arange(50).reshape(5,10)

In [99]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [100]:
arr[2:4,3:7]

array([[23, 24, 25, 26],
       [33, 34, 35, 36]])

In [101]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [102]:
arr[4]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [103]:
import pandas as pd


In [104]:
arr=[10,20,30]

In [105]:
labels=['a','b','c']

In [106]:
d={'a':10,'b':20,'c':30}

In [107]:
arr=np.array(arr)

In [108]:
pd.Series(data=arr)

0    10
1    20
2    30
dtype: int64

In [110]:
pd.Series(data=arr, index=labels)

a    10
b    20
c    30
dtype: int64

In [111]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [112]:
d

{'a': 10, 'b': 20, 'c': 30}

In [113]:
ser1=pd.Series(['USA','India','China','Germany'],[1,2,3,4])

In [114]:
ser1

1        USA
2      India
3      China
4    Germany
dtype: object

In [115]:
ser1=pd.Series([1,2,3,4],['USA','India','China','Germany'])

In [116]:
ser1

USA        1
India      2
China      3
Germany    4
dtype: int64

In [117]:
ser2=pd.Series([1,2,5,4],['USA','India','Italy','Germany'])

In [118]:
ser2

USA        1
India      2
Italy      5
Germany    4
dtype: int64

In [119]:
ser1+ser2

China      NaN
Germany    8.0
India      4.0
Italy      NaN
USA        2.0
dtype: float64

In [124]:
np.random.randn(5,4)

array([[-0.18912513,  0.69428629, -0.8175509 , -0.87325376],
       [ 0.22175099,  1.28074118, -1.3751024 ,  0.75829455],
       [-0.66355503,  0.13196469, -0.08769369,  1.13955687],
       [-0.09394598,  0.77012882, -1.64149641,  0.66291735],
       [-0.56796152,  0.86086003,  0.21552256, -0.90829532]])

In [125]:
df = pd.DataFrame(np.random.randn(5,4), ['A','B','C','D','E'], ['W','X','Y','Z'])

In [126]:
df

W         X         Y         Z
A -0.537381  0.339177 -0.191685 -0.596523
B -1.273572  0.657830 -0.695098 -0.710322
C -0.647823  2.035186  0.263785  2.176401
D -0.291613 -0.642626  0.606001  1.282270
E  0.475855 -1.088514 -0.158442  0.458261

In [128]:
df['W']['B']

-1.2735718607048658

In [130]:
df['new']=df['W']+df['X']

In [131]:
df

W         X         Y         Z       new
A -0.537381  0.339177 -0.191685 -0.596523 -0.198204
B -1.273572  0.657830 -0.695098 -0.710322 -0.615742
C -0.647823  2.035186  0.263785  2.176401  1.387363
D -0.291613 -0.642626  0.606001  1.282270 -0.934239
E  0.475855 -1.088514 -0.158442  0.458261 -0.612659

In [132]:
df.drop(columns='new', axis=1)

W         X         Y         Z
A -0.537381  0.339177 -0.191685 -0.596523
B -1.273572  0.657830 -0.695098 -0.710322
C -0.647823  2.035186  0.263785  2.176401
D -0.291613 -0.642626  0.606001  1.282270
E  0.475855 -1.088514 -0.158442  0.458261

In [133]:
df

W         X         Y         Z       new
A -0.537381  0.339177 -0.191685 -0.596523 -0.198204
B -1.273572  0.657830 -0.695098 -0.710322 -0.615742
C -0.647823  2.035186  0.263785  2.176401  1.387363
D -0.291613 -0.642626  0.606001  1.282270 -0.934239
E  0.475855 -1.088514 -0.158442  0.458261 -0.612659

In [134]:
df.drop(columns='new', axis=1, inplace=True)

In [135]:
df


W         X         Y         Z
A -0.537381  0.339177 -0.191685 -0.596523
B -1.273572  0.657830 -0.695098 -0.710322
C -0.647823  2.035186  0.263785  2.176401
D -0.291613 -0.642626  0.606001  1.282270
E  0.475855 -1.088514 -0.158442  0.458261

In [136]:
df.drop('E')

W         X         Y         Z
A -0.537381  0.339177 -0.191685 -0.596523
B -1.273572  0.657830 -0.695098 -0.710322
C -0.647823  2.035186  0.263785  2.176401
D -0.291613 -0.642626  0.606001  1.282270

In [137]:
df

W         X         Y         Z
A -0.537381  0.339177 -0.191685 -0.596523
B -1.273572  0.657830 -0.695098 -0.710322
C -0.647823  2.035186  0.263785  2.176401
D -0.291613 -0.642626  0.606001  1.282270
E  0.475855 -1.088514 -0.158442  0.458261

In [139]:
df.shape

(5, 4)

In [143]:
df[['X','Y']]

X         Y
A  0.339177 -0.191685
B  0.657830 -0.695098
C  2.035186  0.263785
D -0.642626  0.606001
E -1.088514 -0.158442

In [147]:
#df[[['A','B'],['X','Y']]]

In [148]:
df

W         X         Y         Z
A -0.537381  0.339177 -0.191685 -0.596523
B -1.273572  0.657830 -0.695098 -0.710322
C -0.647823  2.035186  0.263785  2.176401
D -0.291613 -0.642626  0.606001  1.282270
E  0.475855 -1.088514 -0.158442  0.458261

In [152]:
df['X']['A']

0.33917744118315457

In [155]:
df.loc[['A','B'],['W','Y']]

W         Y
A -0.537381 -0.191685
B -1.273572 -0.695098

In [157]:
df

W         X         Y         Z
A -0.537381  0.339177 -0.191685 -0.596523
B -1.273572  0.657830 -0.695098 -0.710322
C -0.647823  2.035186  0.263785  2.176401
D -0.291613 -0.642626  0.606001  1.282270
E  0.475855 -1.088514 -0.158442  0.458261

In [162]:
r='A'
c='X'

In [163]:
df.loc[r,c]

0.33917744118315457

In [164]:
df > 0


W      X      Y      Z
A  False   True  False  False
B  False   True  False  False
C  False   True   True   True
D  False  False   True   True
E   True  False  False   True

In [166]:
df >0

W      X      Y      Z
A  False   True  False  False
B  False   True  False  False
C  False   True   True   True
D  False  False   True   True
E   True  False  False   True

In [168]:
df[df>0]

W         X         Y         Z
A       NaN  0.339177       NaN       NaN
B       NaN  0.657830       NaN       NaN
C       NaN  2.035186  0.263785  2.176401
D       NaN       NaN  0.606001  1.282270
E  0.475855       NaN       NaN  0.458261

In [169]:
df

W         X         Y         Z
A -0.537381  0.339177 -0.191685 -0.596523
B -1.273572  0.657830 -0.695098 -0.710322
C -0.647823  2.035186  0.263785  2.176401
D -0.291613 -0.642626  0.606001  1.282270
E  0.475855 -1.088514 -0.158442  0.458261

In [174]:
df[df['W']<0]['W']

A   -0.537381
B   -1.273572
C   -0.647823
D   -0.291613
Name: W, dtype: float64

In [175]:
df

W         X         Y         Z
A -0.537381  0.339177 -0.191685 -0.596523
B -1.273572  0.657830 -0.695098 -0.710322
C -0.647823  2.035186  0.263785  2.176401
D -0.291613 -0.642626  0.606001  1.282270
E  0.475855 -1.088514 -0.158442  0.458261

In [176]:
df_ser=df>0

In [177]:
df_ser

W      X      Y      Z
A  False   True  False  False
B  False   True  False  False
C  False   True   True   True
D  False  False   True   True
E   True  False  False   True

In [178]:
df_ser=df['W']>0

In [179]:
df_ser

A    False
B    False
C    False
D    False
E     True
Name: W, dtype: bool

In [180]:
df_frame=df[df_ser]

In [181]:
df_frame


W         X         Y         Z
E  0.475855 -1.088514 -0.158442  0.458261

In [182]:
df_frame[['W','Y']]

W         Y
E  0.475855 -0.158442

In [183]:
df

W         X         Y         Z
A -0.537381  0.339177 -0.191685 -0.596523
B -1.273572  0.657830 -0.695098 -0.710322
C -0.647823  2.035186  0.263785  2.176401
D -0.291613 -0.642626  0.606001  1.282270
E  0.475855 -1.088514 -0.158442  0.458261

In [184]:
df[df['W']>0][['W','Y']]

W         Y
E  0.475855 -0.158442

In [190]:
df[(df['W']>0) & (df['Z']>0)][['W','Z']]

W         Z
E  0.475855  0.458261

In [191]:
df.reset_index()

index         W         X         Y         Z
0     A -0.537381  0.339177 -0.191685 -0.596523
1     B -1.273572  0.657830 -0.695098 -0.710322
2     C -0.647823  2.035186  0.263785  2.176401
3     D -0.291613 -0.642626  0.606001  1.282270
4     E  0.475855 -1.088514 -0.158442  0.458261

In [192]:
df2=pd.DataFrame(np.random.randn(5,4),[1,2,3,4,5],[1,2,3,4])

In [193]:
df2

1         2         3         4
1  0.318858 -0.794758 -0.455039  0.486521
2  0.050122  0.665713 -1.714787 -1.290184
3  0.506113  0.015586  0.406477 -1.055364
4 -0.554611  0.016296  0.224668  1.333538
5  0.304601 -1.007892 -1.655465  0.306760

In [198]:
df2

1         2         3         4
1  0.318858 -0.794758 -0.455039  0.486521
2  0.050122  0.665713 -1.714787 -1.290184
3  0.506113  0.015586  0.406477 -1.055364
4 -0.554611  0.016296  0.224668  1.333538
5  0.304601 -1.007892 -1.655465  0.306760

In [199]:
df

W         X         Y         Z
A -0.537381  0.339177 -0.191685 -0.596523
B -1.273572  0.657830 -0.695098 -0.710322
C -0.647823  2.035186  0.263785  2.176401
D -0.291613 -0.642626  0.606001  1.282270
E  0.475855 -1.088514 -0.158442  0.458261

In [205]:
df.loc['A'].loc['X']

0.33917744118315457

In [206]:
d={'a':[1,2,np.nan],'b':[3,np.nan,1],'c':[np.nan,3,1]}

In [207]:
d

{'a': [1, 2, nan], 'b': [3, nan, 1], 'c': [nan, 3, 1]}

In [208]:
df = pd.DataFrame(d)

In [209]:
df

a    b    c
0  1.0  3.0  NaN
1  2.0  NaN  3.0
2  NaN  1.0  1.0

In [213]:
df[df.dropna()]

a   b   c
0 NaN NaN NaN
1 NaN NaN NaN
2 NaN NaN NaN

In [214]:
df.dropna()

Empty DataFrame
Columns: [a, b, c]
Index: []

In [224]:
d={'a':[1,2,np.nan],'b':[3,np.nan,np.nan],'c':[2,3,1]}

In [225]:
df=pd.DataFrame(d)

In [226]:
df

a    b  c
0  1.0  3.0  2
1  2.0  NaN  3
2  NaN  NaN  1

In [219]:
df.dropna()

a    b  c
0  1.0  3.0  2

In [220]:
tdf=df.dropna()

In [221]:
tdf

a    b  c
0  1.0  3.0  2

In [222]:
tdf.dropna(axis=1)

a    b  c
0  1.0  3.0  2

In [223]:
df

a    b  c
0  1.0  3.0  2
1  2.0  NaN  3
2  NaN  1.0  1

In [227]:
df

a    b  c
0  1.0  3.0  2
1  2.0  NaN  3
2  NaN  NaN  1

In [238]:
df.dropna(thresh=2, axis=1)

a  c
0  1.0  2
1  2.0  3
2  NaN  1

df

In [239]:
df

a    b  c
0  1.0  3.0  2
1  2.0  NaN  3
2  NaN  NaN  1

In [240]:
df['a'].fillna(value=df['a'].mean())

0    1.0
1    2.0
2    1.5
Name: a, dtype: float64

In [241]:
df

a    b  c
0  1.0  3.0  2
1  2.0  NaN  3
2  NaN  NaN  1

In [242]:
d={'company':['a','a','b','b','c','c'],'person':[1,2,3,4,5,6],'sales':[100,150,134,233,46,300]}

In [243]:
df=pd.DataFrame(d)

In [244]:
df

company  person  sales
0       a       1    100
1       a       2    150
2       b       3    134
3       b       4    233
4       c       5     46
5       c       6    300

In [257]:
df.groupby('company').describe().loc['a']

person  count      2.000000
        mean       1.500000
        std        0.707107
        min        1.000000
        25%        1.250000
        50%        1.500000
        75%        1.750000
        max        2.000000
sales   count      2.000000
        mean     125.000000
        std       35.355339
        min      100.000000
        25%      112.500000
        50%      125.000000
        75%      137.500000
        max      150.000000
Name: a, dtype: float64

In [258]:
df

company  person  sales
0       a       1    100
1       a       2    150
2       b       3    134
3       b       4    233
4       c       5     46
5       c       6    300

In [262]:
df['company']

0    a
1    a
2    b
3    b
4    c
5    c
Name: company, dtype: object

In [263]:
df

company  person  sales
0       a       1    100
1       a       2    150
2       b       3    134
3       b       4    233
4       c       5     46
5       c       6    300

In [264]:
df2=df

In [265]:
df2

company  person  sales
0       a       1    100
1       a       2    150
2       b       3    134
3       b       4    233
4       c       5     46
5       c       6    300

In [270]:
df2['company'][1]

'b'

In [271]:
df2

company  person  sales
0       a       1    100
1       b       2    150
2       b       3    134
3       b       4    233
4       c       5     46
5       c       6    300

In [272]:
df

company  person  sales
0       a       1    100
1       b       2    150
2       b       3    134
3       b       4    233
4       c       5     46
5       c       6    300

In [273]:
df2['company'][1]='dsf'

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [274]:
df2

company  person  sales
0       a       1    100
1     dsf       2    150
2       b       3    134
3       b       4    233
4       c       5     46
5       c       6    300

In [275]:
df

company  person  sales
0       a       1    100
1     dsf       2    150
2       b       3    134
3       b       4    233
4       c       5     46
5       c       6    300

In [276]:
pwd

'/Users/astitvnagpal'

In [278]:
pd.read_csv('/Users/astitvnagpal/Ghost_Files/Udemy_Courses/MachineLearning_Python/Python-Data-Science-and-Machine-Learning-Bootcamp/Python-for-Data-Analysis/Pandas/example.csv')

FileNotFoundError: File b'/Users/astitvnagpal/Ghost_Files/Udemy_Courses/MachineLearning_Python/Python-Data-Science-and-Machine-Learning-Bootcamp/Python-for-Data-Analysis/Pandas/example.csv' does not exist